name: apiverve_emaildisposablechecker
description: Email Disposable Checker is a simple tool for checking if an email address is disposable. It returns if the email address is disposable or not.
version: 1.1.14
homepage: https://emaildisposablechecker.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/emaildisposablechecker-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
